Syntax 2

SectionVerb {
        EnableSequence [
                cdev "agm"
                cset "iface=MIXER,name='PCM_RT_PROXY-RX-2 rate ch fmt' 0xbb80,0x2,0x2,0x1"
                cset "iface=MIXER,name='PCM100 control' PCM_RT_PROXY-RX-2"
                cset-tlv "iface=MIXER,name='PCM_RT_PROXY-RX-2 metadata' /etc/device_metadata.bin"
                cset-tlv "iface=MIXER,name='PCM100 metadata' /etc/stream_metadata.bin"
                cset-tlv "iface=MIXER,name='PCM100 metadata' /etc/stream_device_metadata.bin"
                cset "iface=MIXER,name='PCM100 connect' PCM_RT_PROXY-RX-2"
        ]
        DisableSequence [
        ]

        Value {
                PlaybackPCM "agm:100,100"
        }
}

SectionDevice."Speaker" {
        EnableSequence [
        ]

        DisableSequence [
        ]

        Value {
                PlaybackChannels "2"
        }
}
